import os
import sys

import psycopg2 as dbapi2


INIT_STATEMENTS = [
    "CREATE TABLE IF NOT EXISTS PERSON (ID SERIAL PRIMARY KEY, NAME VARCHAR(50) UNIQUE NOT NULL, AGE INTEGER)",
    "CREATE TABLE IF NOT EXISTS JOBTITLES (ID SERIAL PRIMARY KEY, JOBNAME VARCHAR(50) UNIQUE NOT NULL)",
    "CREATE TABLE IF NOT EXISTS LEVEL (ID SERIAL PRIMARY KEY, LEVELNAME VARCHAR(50) UNIQUE NOT NULL)",
    "CREATE TABLE IF NOT EXISTS WORKCHART (PERSONID INTEGER REFERENCES PERSON (ID), JOBID INTEGER REFERENCES JOBTITLES (ID), LEVELID INTEGER REFERENCES LEVEL (ID), SALARY INTEGER, PRIMARY KEY (PERSONID))",
    "CREATE TABLE IF NOT EXISTS SERVICE (ID SERIAL PRIMARY KEY, TOWN VARCHAR(20), CAPACITY INTEGER)",
    "CREATE TABLE IF NOT EXISTS TRANSPORTATION (SERVICEID INTEGER REFERENCES SERVICE (ID), PERSONID INTEGER REFERENCES SERVICE (ID), PRIMARY KEY (PERSONID))",
]


def initialize(url):
    with dbapi2.connect(url) as connection: #connection context manager
        cursor = connection.cursor()
        for statement in INIT_STATEMENTS:
            cursor.execute(statement)
        cursor.close()


if __name__ == "__main__":
    url = os.getenv("DATABASE_URL")
    if url is None:
        print("Usage: DATABASE_URL=url python dbinit.py", file=sys.stderr)
        sys.exit(1)
    initialize(url)
